@ECHO OFF
ECHO                                                           ³
ECHO  Please wait while Program Manager Turns off your PC...   ³
ECHO                                                           ³
ECHO -----------------------------------------------------------
CD..
CD..
CD..
GOTO SAFE

:SAFE
EXIT
CLS
ECHO                                                           ³
ECHO  Its now safe to turn off your PC...                      ³
ECHO                                                           ³
PAUSE -----------------------------------------------------------
GOTO SAFE
