@ECHO OFF
CLS
ECHO ---------------------------------------------------------------------
ECHO ³ DOSHELP                                                      QUIT ³
ECHO ---------------------------------------------------------------------
ECHO ³ {PROGHELP} {PROGVER}                                              ³
ECHO ---------------------------------------------------------------------
ECHO.
ECHO   DOSDIRC--------------------Shows The Directory of C:\
ECHO   DOSDIRA--------------------Shows The Directory of A:\
ECHO   DOSHELP--------------------Shows All DOS Commands
ECHO   DOSVER---------------------Displays the Current Version of DOS
ECHO   DOSTIME--------------------Displays your Time configured on DOS
ECHO.
ECHO ---------------------------------------------------------------------
ECHO ³ WAITING FOR INPUT.....                                            ³
ECHO ---------------------------------------------------------------------
