@ECHO OFF
CLS
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё NPGMGT                                                       QUIT Ё
ECHO цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
ECHO Ё {PROGHELP} {PROGVER}                                              Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO.
ECHO   This is a test to see if your DOS Computer will support
ECHO   the new theme in the Panel (SMT)
ECHO.
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё WAITING FOR INPUT.....                                            Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
