@ECHO OFF
CLS
ECHO ---------------------------------------------------------------------
ECHO ³ PROGHELP                                                     QUIT ³
ECHO ---------------------------------------------------------------------
ECHO ³ {PROGHELP} {PROGVER}                                              ³
ECHO ---------------------------------------------------------------------
ECHO.
ECHO   PROGMAN--------------------Displays a Blank page like at start
ECHO   PROGHELP-------------------Shows All Program Manager Commands
ECHO   PROGVER--------------------Displays Version of Program Manager
ECHO   PROGDIR--------------------Shows The Directory of Program Manager
ECHO   HOMELNK--------------------Displays the Link List Director
ECHO   PANEL----------------------Shows a list of settings you can change
ECHO   DOSHELP--------------------Displays DOS Commands
ECHO.
ECHO ---------------------------------------------------------------------
ECHO ³ WAITING FOR INPUT.....                                            ³
ECHO ---------------------------------------------------------------------
