@ECHO OFF
CD..
CD IDQYN
ECHO -----------------------------------------------------------
ECHO                                                           ³
ECHO  Do you want to Delete Or Install Program Manager 1.3?    ³
ECHO  Requirements: MS-DOS 1.00 to 7.10                        ³
ECHO                                                           ³
ECHO ----------------[CANCEL,DELETE,INSTALL]--------------------
