@ECHO OFF
DEL C:\START.BAT
COPY C:\PROGMAN\RESC\SMSN.BAT C:\START.BAT
CD..
CD RESC
CD SMSM
CLS
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё SMS                                                               Ё
ECHO цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO.
ECHO   [!] You Must Restart your Computer for changes to apply. [Y,N]
ECHO.
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё WAITING FOR INPUT.....                                            Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
