@ECHO OFF
CLS
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё DOSHELP                                                      QUIT Ё
ECHO цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
ECHO Ё {PROGHELP} {PROGVER}                                              Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO.
ECHO   DOSDIRC--------------------Shows The Directory of C:\
ECHO   DOSDIRA--------------------Shows The Directory of A:\
ECHO   DOSHELP--------------------Shows All DOS Commands
ECHO   DOSVER---------------------Displays the Current Version of DOS
ECHO   DOSTIME--------------------Displays your Time configured on DOS
ECHO.
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё WAITING FOR INPUT.....                                            Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
