@ECHO OFF
CLS
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё PROGHELP                                                     QUIT Ё
ECHO цддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╢
ECHO Ё {PROGHELP} {PROGVER}                                              Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
ECHO.
ECHO   PROGMAN--------------------Displays a Blank page like at start
ECHO   PROGHELP-------------------Shows All Program Manager Commands
ECHO   PROGVER--------------------Displays Version of Program Manager
ECHO   PROGDIR--------------------Shows The Directory of Program Manager
ECHO   HOMELNK--------------------Displays the Link List Directory
ECHO   DOSHELP--------------------Displays DOS Commands
ECHO.
ECHO зддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд©
ECHO Ё WAITING FOR INPUT.....                                            Ё
ECHO юддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддды
