@ECHO OFF
DEL C:\START.BAT
COPY C:\PROGMAN\RESC\SMSY.BAT C:\START.BAT
CD..
CD RESC
CD SMSM
CLS
ECHO ---------------------------------------------------------------------
ECHO ³ SMS                                                               ³
ECHO ---------------------------------------------------------------------
ECHO ---------------------------------------------------------------------
ECHO.
ECHO   [!] You Must Restart your Computer for changes to apply. [Y,N]
ECHO.
ECHO ---------------------------------------------------------------------
ECHO ³ WAITING FOR INPUT.....                                            ³
ECHO ---------------------------------------------------------------------
